version: "3.9"  # optional since v1.27.0
services:
  sql:
    container_name: mssql
    image: dietermarno/thomasgregmssql:data
    hostname: mssql
    restart: always
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=R353t3282@
    networks:
      - dockerhost
  web_api:
    container_name: webapi
    image: dietermarno/thomasgregcorewebapi:dev
    hostname: webapi
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=R353t3282@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    depends_on:
      - sql
    networks:
      - dockerhost
  web_mvc:
    container_name: webmvc
    image: dietermarno/thomasgregmvc:dev
    hostname: webmvc
    ports:
      - "4200:80"
      - "4201:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=4201
      - ASPNETCORE_Kestrel__Certificates__Default__Password=R353t3282@
      - ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    depends_on:
      - sql
      - web_api
    networks:
      - dockerhost
networks:
  dockerhost:
    driver: bridge
    name: thomasgreg
